# 当 使用 SpringCloudConfig 后,可将此文件上传到git，此内容将不再

#内置的tomcat服务启动监听端口号
server:
  # port: 8888
  port: 10086

#应用名称
spring:
  application:
    name: eureka-server

#EurekaServer配置
eureka:
  client:
    # register-with-eureka: false #此EurekaServer不再注册到其他的注册中心
    # fetch-registry: false       #不再从其他中心中心拉取服务器信息
    service-url:
      #defaultZone: http://localhost:${server.port}/eureka #注册中心访问地址
      defaultZone: http://localhost:10087/eureka #指向高可用另外一台Eureka服务器
  server:
    enable-self-preservation: false   # Eureka开启自动保护模式
    eviction-interval-timer-in-ms: 4000
